model_name_or_path: Qwen/Qwen3.5-9B
torch_dtype: bfloat16
device: cuda:0
seed: 42
use_chat_template: true
system_prompt: '/no_think'
enable_thinking: false
apply_steer_hparam_paths:
- /users/acp25mk/cross-lingual-caa/hparams/Steer/caa_hparams/apply_caa_layer15_m-1.5.yaml
steer_vector_load_dir:
- /users/acp25mk/cross-lingual-caa/vectors/Qwen3.5-9B/sycophancy/caa_vector_multiple_choice
generation_data:
- /users/acp25mk/cross-lingual-caa/data/sycophancy/zh/eval.json
generation_data_size: null
generation_output_dir: /users/acp25mk/cross-lingual-caa/results/qwen35_syco_zh_m-1.5_layer15
num_responses: 1
steer_from_end_position: false
generate_orig_output: true
generation_params:
  max_new_tokens: 512
  do_sample: false
  temperature: 0.0
