model_name_or_path: Qwen/Qwen3.5-9B
torch_dtype: bfloat16
device: cuda:0
seed: 42
use_chat_template: true
system_prompt: 'Answer with only (A) or (B). /no_think'
apply_steer_hparam_paths:
- /users/acp25mk/cross-lingual-caa/hparams/Steer/caa_hparams/apply_caa_layer22_m1.5.yaml
steer_vector_load_dir:
- /users/acp25mk/cross-lingual-caa/vectors/Qwen3.5-9B/truthfulqa/caa_vector/truthfulqa_en/caa_vector_multiple_choice
generation_data:
- /users/acp25mk/cross-lingual-caa/data/truthfulqa/kk/eval.json
generation_data_size: null
generation_output_dir: /users/acp25mk/cross-lingual-caa/results/tqa_qwen35_kk_m1.5_layer22
num_responses: 1
steer_from_end_position: false
generate_orig_output: true
generation_params:
  max_new_tokens: 64
  do_sample: false
  temperature: 0.0
enable_thinking: false
