model_name_or_path: allenai/Olmo-3-7B-Instruct
torch_dtype: bfloat16
device: cuda:0
seed: 42
use_chat_template: true
system_prompt: 'Answer with only (A) or (B).'

steer_train_hparam_paths:
 - hparams/Steer/caa_hparams/generate_caa_olmo3.yaml
steer_train_dataset:
 - truthfulqa_kk
save_vectors: True
steer_vector_output_dirs:
 - vectors/Olmo-3-7B-Instruct/truthfulqa/caa_vector

vllm_enable: false
