model_name_or_path: Qwen/Qwen2.5-7B-Instruct
torch_dtype: bfloat16
device: cuda:0
seed: 42
use_chat_template: True
system_prompt: ''

steer_train_hparam_paths:
 - hparams/Steer/caa_hparams/generate_caa_layers12_26.yaml
steer_train_dataset:
 - semeval_es
save_vectors: True
steer_vector_output_dirs:
 - vectors/Qwen2.5-7B-Instruct-semeval-es

vllm_enable: false
